on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - simple 
    steps:
      - uses: actions/checkout@v2
      - name: buf-setup
        uses: bufbuild/buf-setup-action@v0.7.0
      - name: Lint ${{ matrix.target }} directory with Buf
        run: buf lint 
        working-directory: ./${{ matrix.target }}
